spring:
  application:
    name: sistema-reclamacoes

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres-sistema-reclamacoes